# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6228ad7ea4c0d08d73e62db2310d33c6ca85cacad196039887fc7ded0ef8722307dbe32243efbade07fac0b5bb75043ab3907186e0e7eca5d4ba4571caf13c

test:
  secret_key_base: 7ce51ceb827ab8fbfb9a947eca0647c3ced932c603688df1cc7b60fc5a59b649a37b5051c39c3e7df3eaa24a096cd5e170906d7a1a472b5b8cecfb8243848e4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
